### ISSUE TITLE
Changing maps api

### ISSUE THREAD

**Issue by Brozz** [mndsilva/hallooou-HTML5-responsive-template#1]
how can I change the maps api location?
I have tried a custom JS file but than some other parts of the website are changing than.
I hope you can help.

**Comment by mauritiusdsilva** [comment]
You need to go to the "Google map API" section in the JS file, right after the function is the "set your google maps parameters" block, add your latitude and longitude values here.

**Comment by Brozz** [comment]
Thanks fot your help, I looked over it all the time sorry.
I want to compliment you with this amazing template :p

**Comment by mauritiusdsilva** [comment]
Glad you liked it. Good luck with the implementation of the theme.
