### ISSUE TITLE
Error message when using contact form

### ISSUE THREAD

**Issue by Brozz** [mndsilva/hallooou-HTML5-responsive-template#2]
Hello,

First Great template!!
I have a question.
Every time we use the contact form we get the following error message:
{"type":"error","text":"Sorry Request must be Ajax POST"}

is there a way to solve this?

Thanks in advanced,

**Comment by mauritiusdsilva** [comment]
Hi,

This error message shows up when there's an error in the JS file. Previously users have had this issue and it was the misconfiguration of Google Map API code that caused this error message to show up. If you have removed Google Map API from your site make sure to remove the API code block from the JS file.

Hope this helps.

**Comment by Brozz** [comment]
Hey,

Thanks a lot that solved the issue.
