### ISSUE TITLE
Map not displaying anymore...

### ISSUE THREAD

**Issue by shnabz** [mndsilva/hallooou-HTML5-responsive-template#3]
Hey, I have been using this template for a while, thank you btw I love it. All of a sudden the map stopped displaying, instead it is just the background grey colour. This isn't due to a change I have made, this problem exists in your template. Maybe Google changed something?

**Comment by mauritiusdsilva** [comment]
Hello, I think there was an issue with Google map, it's working fine now, do check from your end. I would also suggest you generate your own Google map API key to use on your website, there are too many request made from the included demo key and it might exceed the daily usage limit of Google map API without warning.

**Comment by shnabz** [comment]
Yes the first thing I did was generate my own API key because I thought that might have been the issue. It's seems to be working fine now, must have been Google's issue. Thanks for taking a look.
