### ISSUE TITLE
Auto-play Video

### ISSUE THREAD

**Issue by brunomosciatti** [mndsilva/hallooou-HTML5-responsive-template#4]
How can I decrease the autoplay delay from youtube video example?

**Comment by mauritiusdsilva** [comment]
The YouTube player version of the template is using YTPlayer plugin, you can find more info on the plugin here: https://github.com/pupunzi/jquery.mb.YTPlayer/wiki. 

You need to specifically look at is this part:
**startAt**: 20 (number) Set the seconds the video should start at.
**stopAt**: 20 (number) Set the seconds the video should stop at. If 0 is ignored.
